import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :poker, PokerWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# force_ssl only applies to cloud/host deployments.
# On Nerves the Pi serves plain HTTP on its private WiFi hotspot.
if Mix.target() == :host do
  config :poker, PokerWeb.Endpoint,
    force_ssl: [
      rewrite_on: [:x_forwarded_proto],
      exclude: [
        # paths: ["/health"],
        hosts: ["localhost", "127.0.0.1"]
      ]
    ]
end

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
